export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SHOW_ADD_PRODUCT_PANE = 'SHOW_ADD_PRODUCT_PANE';
export const HIDE_ADD_PRODUCT_PANE = 'HIDE_ADD_PRODUCT_PANE';
export const DO_ADD_PRODUCT = 'DO_ADD_PRODUCT';
export const COMPARE_PRODUCT = 'COMPARE_PRODUCT';
